# Generated by Django 3.1.2 on 2020-10-31 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_like_post_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='timePosted',
            field=models.DateTimeField(),
        ),
    ]
