# Generated by Django 3.1.2 on 2020-10-21 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20201021_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closedauction',
            name='dateended',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='closedauction',
            name='winningbid',
            field=models.IntegerField(),
        ),
    ]
